version: '3.4'

networks: 
  dockersql-network:
    driver: bridge

services:
  quotation.api:
    image: ${DOCKER_REGISTRY-}quotationapi
    build:
      context: .
      dockerfile: Quotation.Api/Dockerfile
    networks:
      - dockersql-network
    depends_on:
      - db
  db:
    container_name: dockersqldatabase
    image: microsoft/mssql-server-linux
    networks:
        - dockersql-network
    environment:
      - SA_PASSWORD=123mudar...
      - ACCEPT_EULA=Y
    ports:
      - "1401:1433"
